#!/usr/bin/env python
# -*- coding: utf-8 -*-

APPNAME = 'simple-doc-search'
VERSION = '1.0.0'

top = '.'
out = '_build'

import urllib
import os
import tarfile

import yaml

from waflib.Task import Task
from waflib.Build import BuildContext

# DotCloud uses version 3.4.
SOLR_VERSION = '3.4.0'
SOLR_PACKAGE = 'apache-solr-%s.tgz' % (SOLR_VERSION,)
SOLR_MIRROR = 'http://ftp.riken.jp/net/apache/lucene/solr/%s/%s' % (SOLR_VERSION, SOLR_PACKAGE)


class solr(Task):

    def run(self):
        url = self.env['mirror']
        p = self.outputs[0].abspath()
        if not os.path.exists(p):
            urllib.urlretrieve(url, p)
        d, _ = os.path.splitext(p)
        if not os.path.exists(d):
            with tarfile.open(p) as tar:
                tar.extractall()


class debug(BuildContext):
    cmd = 'debug'
    variant = 'debug'


def options(ctx):
    ctx.add_option('--solr', default='http://localhost:8983/solr',
            help="Development Solr server URL.")


def configure(ctx):
    ctx.exec_command("pip install -r conf/requirements.txt")
    ctx.find_program('java')
    ctx.find_program('yuicompressor')
    ctx.find_program('nosetests')


def build(bld):
    env = bld.env.derive()
    env['mirror'] = SOLR_MIRROR
    solr_task = solr(env=env)
    solr_task.set_outputs(bld.path.find_or_declare(SOLR_PACKAGE))
    bld.add_to_group(solr_task)

    info = bld.path.find_resource('conf/dotcloud-info.yml')
    if info:
        c = yaml.load(info.read())
        SOLR_SERVER = c['search']['url']
        SOLR_PASSWORD = c['search']['config']['solr_dotcloud_password']
        print SOLR_SERVER
        print SOLR_PASSWORD
        # XXX: USE ON TEST PHASE
    else:
        raise SystemExit("`waf dotcloud_info` at first.")


def test(ctx):
    t = ctx.path.ant_glob('tests/*.py')
    files = [f.abspath() for f in t]
    ctx.exec_command('nosetests -vv ' + ' '.join(files))


def dotcloud_info(ctx):
    info = ctx.path.make_node('conf/dotcloud-info.yml')
    ctx.exec_command('dotcloud info docsearch >%s' % (info.abspath(),))


def run_solr(ctx):
    d, _ = os.path.splitext(SOLR_PACKAGE)
    ex = ctx.path.find_dir(d + '/example')
    s = ctx.path.find_dir('solr')
    ctx.exec_command(['java', '-Dsolr.solr.home=%s' % (s.abspath(),),
                      '-jar', 'start.jar'], cwd=ex.abspath())

# vim: set et ts=4 sw=4 cindent fileencoding=utf-8 :
