Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define :notebook do |node|
    node.vm.provider :virtualbox do |v|
      v.name = "jupyternb-notebook-vm"
      v.customize ["modifyvm", :id, "--memory", "4096"]
    end
    node.vm.network :private_network, ip: "192.168.50.101"
    node.vm.hostname = "notebook1"
    # node.disksize.size = "50GB"
  end

  config.vm.define :notebook_mini do |node|
    node.vm.box = "bento/ubuntu-14.04"
    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    node.vm.network :private_network, ip: "192.168.50.102"
  end

  config.vm.define :webproxy do |node|
    node.vm.provider :virtualbox do |v|
      v.name = "jupyternb-webproxy-vm"
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    node.vm.network :private_network, ip: "192.168.50.100"
    node.vm.hostname = "webproxy1"
  end

  config.vm.define 'controller' do |machine|
    machine.vm.provider :virtualbox do |v|
      v.name = "jupyternb-ctrlmach-vm"
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    machine.vm.network "private_network", ip: "192.168.50.10"
    machine.vm.hostname = "controller1"
    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook         = "localdev.yml"
      ansible.inventory_path   = "environments/vagrant"
      ansible.limit            = "all"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.verbose          = true
      ansible.install          = true
      ansible.install_mode     = "pip"
      ansible.version          = "2.4.0.0"
    end
  end

end
