production:
    mysql:
        host: 192.168.0.22
        port: 3306
        username: product
        password: secret
    mongodb:
        host: 192.168.0.22
        port: 27017

stage:
    mysql:
        host: 192.168.0.22
        port: 3306
        username: manager
        password: manager
    mongodb:
        host: 192.168.0.22
        port: 27018

test:
    mysql:
        host: localhost
        port: 3306
        username: developer
        password: developer
    mongodb:
        host: localhost
        port: 27017

development:
    mysql:
        host: localhost
        port: 3306
        username: anonymous
        password: anonymous
    mongodb:
        host: localhost
        port: 27017
