FROM ubuntu:14.04
MAINTAINER Shigeru Kitazaki <skitazaki@gmail.com>

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y curl git
RUN apt-get install -y ruby-compass
RUN apt-get clean

RUN mkdir /nodejs && curl http://nodejs.org/dist/v0.10.31/node-v0.10.31-linux-x64.tar.gz | tar xvzf - -C /nodejs --strip-components=1
ENV PATH $PATH:/nodejs/bin

RUN npm install -g bower grunt-cli

# Basic environment setup.
RUN locale-gen  en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN adduser --disabled-password nodejs-user

RUN mkdir /app && chown nodejs-user /app
WORKDIR /app

USER nodejs-user
ENV HOME /home/nodejs-user

# Set build triggers.
ONBUILD ADD package.json /app/
ONBUILD RUN npm install
ONBUILD ADD bower.json /app/
ONBUILD RUN bower install
ONBUILD ADD . /app

