application: jpgridmap
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /coordinates/.*
  script: main.app

- url: /grid/.*
  script: main.app

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /styles
  static_dir: dist/styles

- url: /scripts
  static_dir: dist/scripts

- url: /bower_components
  static_dir: dist/bower_components

- url: /
  static_files: dist/index.html
  upload: dist/index\.html

libraries:
- name: webapp2
  version: "2.5.2"
