---

nginx_server_tokens: "off"
nginx_remove_default_vhost: yes

nginx_upstreams:
  - name: jupyternb_server
    servers: "{{ jupyternb_servers }}"

nginx_vhosts:
  - server_name: "{{ webproxy_server_name }}"
    extra_parameters: |
      location {{ jupyternb_prefix }}/ {
          proxy_pass http://jupyternb_server;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_buffering off;
      }
      location ~* {{ jupyternb_prefix }}/(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
          proxy_pass http://jupyternb_server;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 86400;
      }
