#!/usr/bin/env python
# -*- coding: utf-8 -*-

APPNAME = 'pep8-test'
VERSION = '1.0.0'

top = '.'
out = '_build'


def configure(ctx):
    ctx.find_program('pep8')


from waflib.Task import Task

class cp(Task):
    def run(self):
        return self.exec_command('cp %s %s' % (
                self.inputs[0].abspath(), self.outputs[0].abspath()
            ))

class pep8(Task):
    def run(self):
        return self.exec_command('pep8 %s' % (self.inputs[0].abspath(),))

def build(bld):
    f = bld.path.find_resource('pep8-test.py')
    t1 = pep8(env=bld.env)
    t1.set_inputs(f)
    t2 = cp(env=bld.env)
    t2.set_inputs(f.get_src())
    t2.set_outputs(f.get_bld())
    t2.set_run_after(t1)
    bld.add_to_group(t1)
    bld.add_to_group(t2)


# vim: set et ts=4 sw=4 cindent fileencoding=utf-8 :
