# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install ansible
            sudo pip install ansible-lint

      - save_cache:
          paths:
            - ./roles
          key: v1-dependencies-{{ checksum "requirements.yml" }}

      - run:
          name: show ansible and ansible-lint version
          command: |
            ansible --version
            ansible-lint --version

      - run:
          name: lint ansible playbook
          command: |
            ansible-lint vagrant.yml \
                         --exclude=roles/deimosfr.neo4j \
                         --exclude=roles/geerlingguy.ntp \
                         --exclude=roles/bertvv.hosts \
                         --exclude=roles/rvm_io.ruby \
                         --exclude=roles/ansiblebit.oracle-java
